/*
 * Automatically generated make config: don't edit
 */
#define CONFIG_ATHRS27_PHY 1
#define ATHR_GMAC0_MII_PHY ATHR_S27_PHY
#define ATHR_GMAC1_MII_PHY ATHR_S27_PHY
#define ATHR_GMAC0_MII ATHR_MII
#define GMAC0_MII 1
#define ATHR_GMAC1_MII ATHR_RGMII
#define ATH_GE0_IS_CONNECTED 1
#define ATH_GE1_IS_CONNECTED 1
#define CONFIG_ATH_LEN_PER_TX_DS 1536
#define CONFIG_ATH_NUMBER_TX_PKTS  511
#define CONFIG_ATH_NUMBER_RX_PKTS   128
#define CONFIG_ATH_NUMBER_TX_PKTS_1 511
#define CONFIG_ATH_NUMBER_RX_PKTS_1 128
#define CONFIG_ATH_MAC_LOCATION 0xbfff0000
#define ATH_GMAC_TXQUEUELEN 1000
#define CONFIG_GMAC0_RXFCTL 1
#define CONFIG_GMAC0_TXFCTL 1
#define CONFIG_GMAC1_RXFCTL 1
#define CONFIG_GMAC1_TXFCTL 1
#define CONFIG_ATH_LINK_INTR 1
#define CONFIG_ATH_GPIO_LED 1
#define CONFIG_ATH_DMA_CHECK 1
#define CONFIG_ATHR_RX_TASK 1
#define CONFIG_ATHR_RX_PKTS_CNT 18
#define ATH_GMAC_TXQUEUELEN 1000
#define CONFIG_GMAC_RXTIMER 0
#define ETHDEBUG_ENABLED 0
